name: Generate Isometric Calendar

on:
  # Roda automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *"
  # Permite rodar manualmente a qualquer momento
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Isometric Contribution Graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Você pode gerar um PAT se quiser repositórios privados, ou omitir essa linha para focar apenas em públicos
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Mostra os últimos 6 meses (mais minimalista que o ano inteiro)
          config_timezone: America/Manaus

      # Salva a imagem gerada na branch de saída
      - name: Deploy to GitHub Pages or Output Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: output
